spring:
  application:
    name: t1-java-demo
  datasource:
    jdbcUrl: jdbc:h2:mem:test
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  liquibase:
    enabled: false
    default-schema: public
    change-log: db/changelog/db.changelog-master.xml
    driver-class-name: org.h2.Driver
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:t1_demo
    user: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
security:
  token: tstrs4g434wyhser5htstrs4g434wyhser5htstrs4g434wyhser5htstrs4g434wyhser5htstrs4g434wyhser5h
  expiration: 86400000

logging:
  level:
    ROOT: INFO
    ru.t1.java.demo.controller.ClientController: DEBUG

t1:
  scan-path: ru.t1.java.demo
  kafka:
    bootstrap:
      server: localhost:9092
    consumer:
      group-id: t1-demo
      account-group-id: t1-demo-account
      transaction-group-id: t1-demo-transaction
      transaction-error-group-id: t1-demo-transaction-error
      max.poll.records: 10
    producer:
      enable: true
    topic:
      client_registration: client_registration
      client_id_registered: client_registered
      account: t1_demo_accounts
      account-registered: t1_demo_accounts_registered
      t1_demo_client_transactions: t1_demo_client_transactions
      transaction-registered: t1_demo_transactions_registered
      transaction_error: t1_demo_client_transaction_errors
      metric: t1_demo_metric_trace
      error: t1_demo_error_trace
    listener:
      poll-timeout: 1000
  aop:
    execution-time-threshold: 3
  schedule:
    transaction:
      resend:
        period: 10000
integration:
  url: http://localhost:8088
  resource: /bsc-wire-mock/api/client/check
  retry-count: 3
  retry-backoff: 1000