-- liquibase formatted sql

-- changeset osipov_ko:add_role
CREATE TABLE IF NOT EXISTS role
(
    id   BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20)
);


-- changeset osipov_ko:add_users
CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login    VARCHAR(20) UNIQUE,
    email    VARCHAR(50) UNIQUE,
    password VARCHAR(120)
);

-- changeset osipov_ko:add_user_roles
CREATE TABLE IF NOT EXISTS user_roles
(
    role_id BIGINT NOT NULL REFERENCES role(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

-- changeset osipov_ko:add_roles
-- changeset osipov_ko:add_roles_if_not_exist
INSERT INTO role (name)
SELECT 'ROLE_USER'
WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'ROLE_USER');
INSERT INTO role (name)
SELECT 'ROLE_ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'ROLE_ADMIN');
INSERT INTO role (name)
SELECT 'ROLE_MODERATOR'
WHERE NOT EXISTS (SELECT 1 FROM role WHERE name = 'ROLE_MODERATOR');
